In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
data = pd.read_csv("Coursera.csv")

In [3]:
data.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [4]:
data.shape

(3522, 7)

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3522 entries, 0 to 3521
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Course Name         3522 non-null   str
 1   University          3522 non-null   str
 2   Difficulty Level    3522 non-null   str
 3   Course Rating       3522 non-null   str
 4   Course URL          3522 non-null   str
 5   Course Description  3522 non-null   str
 6   Skills              3522 non-null   str
dtypes: str(7)
memory usage: 192.7 KB

In [6]:
data.isnull().sum()

Course Name           0
University            0
Difficulty Level      0
Course Rating         0
Course URL            0
Course Description    0
Skills                0
dtype: int64

In [7]:
data['Difficulty Level'].value_counts()

Difficulty Level
Beginner          1444
Advanced          1005
Intermediate       837
Conversant         186
Not Calibrated      50
Name: count, dtype: int64

In [8]:
data['Course Rating'].value_counts()

Course Rating
4.7               740
4.6               623
4.8               598
4.5               389
4.4               242
4.9               180
4.3               165
4.2               121
5                  90
4.1                85
Not Calibrated     82
4                  51
3.8                24
3.9                20
3.7                18
3.6                18
3.5                17
3.4                13
3                  12
3.2                 9
3.3                 6
2.9                 6
2.6                 2
2.8                 2
2.4                 2
1                   2
2                   1
3.1                 1
2.5                 1
1.9                 1
2.3                 1
Name: count, dtype: int64

In [9]:
data['University'].value_counts()

University
Coursera Project Network                      562
University of Illinois at Urbana-Champaign    138
Johns Hopkins University                      110
University of Colorado Boulder                101
University of Michigan                        101
                                             ...
University of Nebraska                          1
Pontificia Universidad Cat�lica de Chile        1
VMware                                          1
E-Learning Development Fund                     1
The World Bank Group                            1
Name: count, Length: 184, dtype: int64

In [10]:
data['Course Name']

0       Write A Feature Length Screenplay For Film Or ...
1       Business Strategy: Business Model Canvas Analy...
2                           Silicon Thin Film Solar Cells
3                                    Finance for Managers
4            Retrieve Data using Single-Table SQL Queries
                              ...
3517    Capstone: Retrieving, Processing, and Visualiz...
3518                     Patrick Henry: Forgotten Founder
3519    Business intelligence and data analytics: Gene...
3520                                  Rigid Body Dynamics
3521    Architecting with Google Kubernetes Engine: Pr...
Name: Course Name, Length: 3522, dtype: str

In [11]:
data.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [12]:
data.columns

Index(['Course Name', 'University', 'Difficulty Level', 'Course Rating',
       'Course URL', 'Course Description', 'Skills'],
      dtype='str')

In [13]:
data = data[['Course Name', 'Difficulty Level', 'Course URL', 'Course Description', 'Skills']]

In [14]:
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Beginner,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Beginner,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,Advanced,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,Intermediate,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Beginner,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [15]:
data['Course Name'] = data['Course Name'].str.replace(' ', ',')
data['Course Name'] = data['Course Name'].str.replace(':', '')
data['Course Name'] = data['Course Name'].str.replace(',,', ',')

data['Course Description'] = data['Course Description'].str.replace(' ', ',')
data['Course Description'] = data['Course Description'].str.replace(',,', ',')
data['Course Description'] = data['Course Description'].str.replace(':', '')
data['Course Description'] = data['Course Description'].str.replace('_', '')
data['Course Description'] = data['Course Description'].str.replace('(', '')
data['Course Description'] = data['Course Description'].str.replace(')', '')

data['Skills'] = data['Skills'].str.replace('(', '')
data['Skills'] = data['Skills'].str.replace(')', '')

In [16]:
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",Beginner,https://www.coursera.org/learn/write-a-feature...,"Write,a,Full,Length,Feature,Film,Script,In,thi...",Drama Comedy peering screenwriting film D...
1,"Business,Strategy,Business,Model,Canvas,Analys...",Beginner,https://www.coursera.org/learn/canvas-analysis...,"By,the,end,of,this,guided,project,you,will,be,...",Finance business plan persona user experienc...
2,"Silicon,Thin,Film,Solar,Cells",Advanced,https://www.coursera.org/learn/silicon-thin-fi...,"This,course,consists,of,a,general,presentation...",chemistry physics Solar Energy film lambda...
3,"Finance,for,Managers",Intermediate,https://www.coursera.org/learn/operational-fin...,"When,it,comes,to,numbers,there,is,always,more,...",accounts receivable dupont analysis analysis...
4,"Retrieve,Data,using,Single-Table,SQL,Queries",Beginner,https://www.coursera.org/learn/single-table-sq...,"In,this,course,you�ll,learn,how,to,effectively...",Data Analysis select sql database management...

In [17]:
data.columns

Index(['Course Name', 'Difficulty Level', 'Course URL', 'Course Description',
       'Skills'],
      dtype='str')

In [18]:
data['tags'] = data['Course Name'] + data['Difficulty Level'] + data['Course Description'] + data['Skills']

In [19]:
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills,tags
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",Beginner,https://www.coursera.org/learn/write-a-feature...,"Write,a,Full,Length,Feature,Film,Script,In,thi...",Drama Comedy peering screenwriting film D...,"Write,A,Feature,Length,Screenplay,For,Film,Or,..."
1,"Business,Strategy,Business,Model,Canvas,Analys...",Beginner,https://www.coursera.org/learn/canvas-analysis...,"By,the,end,of,this,guided,project,you,will,be,...",Finance business plan persona user experienc...,"Business,Strategy,Business,Model,Canvas,Analys..."
2,"Silicon,Thin,Film,Solar,Cells",Advanced,https://www.coursera.org/learn/silicon-thin-fi...,"This,course,consists,of,a,general,presentation...",chemistry physics Solar Energy film lambda...,"Silicon,Thin,Film,Solar,CellsAdvancedThis,cour..."
3,"Finance,for,Managers",Intermediate,https://www.coursera.org/learn/operational-fin...,"When,it,comes,to,numbers,there,is,always,more,...",accounts receivable dupont analysis analysis...,"Finance,for,ManagersIntermediateWhen,it,comes,..."
4,"Retrieve,Data,using,Single-Table,SQL,Queries",Beginner,https://www.coursera.org/learn/single-table-sq...,"In,this,course,you�ll,learn,how,to,effectively...",Data Analysis select sql database management...,"Retrieve,Data,using,Single-Table,SQL,QueriesBe..."

In [20]:
data['tags'].iloc[1]

'Business,Strategy,Business,Model,Canvas,Analysis,with,MiroBeginnerBy,the,end,of,this,guided,project,you,will,be,fluent,in,identifying,and,creating,Business,Model,Canvas,solutions,based,on,previous,high-level,analyses,and,research,data.,This,will,enable,you,to,identify,and,map,the,elements,required,for,new,products,and,services.,Furthermore,it,is,essential,for,generating,positive,results,for,your,business,venture.,This,guided,project,is,designed,to,engage,and,harness,your,visionary,and,exploratory,abilities.,You,will,use,proven,models,in,strategy,and,product,development,with,the,Miro,platform,to,explore,and,analyse,your,business,propositions.,,We,will,practice,critically,examining,results,from,previous,analysis,and,research,results,in,deriving,the,values,for,each,of,the,business,model,sections.Finance  business plan  persona user experience  business model canvas  Planning  Business  project  Product Development  presentation  Strategy business business-strategy'

In [21]:
new_df = data[['Course Name','Difficulty Level', 'Course URL', 'tags']]

In [22]:
new_df["Course Name"] = data['Course Name'].str.replace(',', ' ')

In [23]:
new_df.rename(columns = {
    'Course Name': 'course_name', 
    'Difficulty Level': 'difficulty_level', 
    'Course URL': 'course_url'
}, inplace = True)

In [24]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [25]:
new_df.head()

,course_name,difficulty_level,course_url,tags
0,Write A Feature Length Screenplay For Film Or ...,Beginner,https://www.coursera.org/learn/write-a-feature...,"write,a,feature,length,screenplay,for,film,or,..."
1,Business Strategy Business Model Canvas Analys...,Beginner,https://www.coursera.org/learn/canvas-analysis...,"business,strategy,business,model,canvas,analys..."
2,Silicon Thin Film Solar Cells,Advanced,https://www.coursera.org/learn/silicon-thin-fi...,"silicon,thin,film,solar,cellsadvancedthis,cour..."
3,Finance for Managers,Intermediate,https://www.coursera.org/learn/operational-fin...,"finance,for,managersintermediatewhen,it,comes,..."
4,Retrieve Data using Single-Table SQL Queries,Beginner,https://www.coursera.org/learn/single-table-sq...,"retrieve,data,using,single-table,sql,queriesbe..."

In [26]:
new_df.shape

(3522, 4)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv = CountVectorizer(max_features=5000, stop_words = 'english')

In [29]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [30]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [31]:
import nltk
from nltk.stem.porter import PorterStemmer

In [32]:
ps = PorterStemmer()

In [33]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [34]:
new_df['tags'] = new_df['tags'].apply(stem)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity = cosine_similarity(vectors)

In [37]:
def recommend(course):
    matches = new_df[new_df['course_name'] == course]
    if matches.empty:
        return f"Course '{course}' not found."
    course_index = matches.index[0]
    # ...rest of your code...
    distance = similarity[course_index]
    course_list = sorted(list(enumerate(distance)), reverse = True, key = lambda x:x[1])[1:7]
    
    recommended_courses = []
    for i in course_list:
        course_name = new_df.iloc[i[0]].course_name
        course_url = new_df.iloc[i[0]].course_url
        recommended_courses.append({'name': course_name, 'url': course_url})
    return recommended_courses

In [38]:
new_df.head()

,course_name,difficulty_level,course_url,tags
0,Write A Feature Length Screenplay For Film Or ...,Beginner,https://www.coursera.org/learn/write-a-feature...,"write,a,feature,length,screenplay,for,film,or,..."
1,Business Strategy Business Model Canvas Analys...,Beginner,https://www.coursera.org/learn/canvas-analysis...,"business,strategy,business,model,canvas,analys..."
2,Silicon Thin Film Solar Cells,Advanced,https://www.coursera.org/learn/silicon-thin-fi...,"silicon,thin,film,solar,cellsadvancedthis,cour..."
3,Finance for Managers,Intermediate,https://www.coursera.org/learn/operational-fin...,"finance,for,managersintermediatewhen,it,comes,..."
4,Retrieve Data using Single-Table SQL Queries,Beginner,https://www.coursera.org/learn/single-table-sq...,"retrieve,data,using,single-table,sql,queriesbe..."

In [39]:
recommend("Retrieve Data using Single-Table SQL Queries")

[{'name': 'Creating Database Tables with SQL',
  'url': 'https://www.coursera.org/learn/creating-database-tables-with-sql'},
 {'name': 'Manipulating Data with SQL',
  'url': 'https://www.coursera.org/learn/manipulating-data-with-sql'},
 {'name': 'Create Relational Database Tables Using SQLiteStudio',
  'url': 'https://www.coursera.org/learn/create-relational-database-table-sqlitestudio'},
 {'name': 'Retrieve Data with Multiple-Table SQL Queries',
  'url': 'https://www.coursera.org/learn/multiple-table-sql-queries'},
 {'name': 'Advanced SQL Retrieval Queries in SQLiteStudio',
  'url': 'https://www.coursera.org/learn/Advanced-sql-retrieval-queries-in-sqlitestudio'},
 {'name': 'Relational Database Support for Data Warehouses',
  'url': 'https://www.coursera.org/learn/dwrelational'}]

In [40]:
import pickle

In [41]:
pickle.dump(similarity, open("models/similarity.pkl", "wb"))
pickle.dump(new_df[['course_name','difficulty_level', 'course_url']].to_dict('records'), open("models/course_list.pkl", "wb"))
pickle.dump(new_df[['course_name','difficulty_level', 'course_url']], open("models/courses.pkl", "wb"))